shadow:
  invoker:
    node-id: 1
    panel:
      url: http://panel.example.com
      username: username
      password: password
    executable: /usr/bin/env bash /usr/local/shadow/run.sh
    conf-location: /usr/local/shadow/mudb.json