spring:
  dubbo:
    registry:
      address: zookeeper://localhost:2181
shadow:
  invoker:
    executable: /usr/bin/env python /usr/local/shadow/server.py
    conf-location: /usr/local/shadow/mudb.json