spring:
  dubbo:
    registry:
      address: zookeeper://localhost:2181
shadow:
  invoker:
    node-id: 1
    executable: /bin/bash /usr/local/shadow/run.sh
    conf-location: /usr/local/shadow/mudb.json